/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * GeneralLiabilityCommercialPolicy
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-03T11:30:23.717Z[GMT]")
public class GeneralLiabilityCommercialPolicy extends Policy {
  @SerializedName("homeBusiness")
  private Boolean homeBusiness = null;

  @SerializedName("businessNumberOfLocations")
  private Integer businessNumberOfLocations = null;

  @SerializedName("businessOwnershipStructure")
  private Objekt businessOwnershipStructure = null;

  @SerializedName("businessNumberOfEmployees")
  private String businessNumberOfEmployees = null;

  @SerializedName("industryType")
  private String industryType = null;

  public GeneralLiabilityCommercialPolicy homeBusiness(Boolean homeBusiness) {
    this.homeBusiness = homeBusiness;
    return this;
  }

   /**
   * Boolean value indicating whether the business is run from a home address
   * @return homeBusiness
  **/
  @Schema(description = "Boolean value indicating whether the business is run from a home address")
  public Boolean isHomeBusiness() {
    return homeBusiness;
  }

  public void setHomeBusiness(Boolean homeBusiness) {
    this.homeBusiness = homeBusiness;
  }

  public GeneralLiabilityCommercialPolicy businessNumberOfLocations(Integer businessNumberOfLocations) {
    this.businessNumberOfLocations = businessNumberOfLocations;
    return this;
  }

   /**
   * The number of locations on the insurance covers
   * @return businessNumberOfLocations
  **/
  @Schema(description = "The number of locations on the insurance covers")
  public Integer getBusinessNumberOfLocations() {
    return businessNumberOfLocations;
  }

  public void setBusinessNumberOfLocations(Integer businessNumberOfLocations) {
    this.businessNumberOfLocations = businessNumberOfLocations;
  }

  public GeneralLiabilityCommercialPolicy businessOwnershipStructure(Objekt businessOwnershipStructure) {
    this.businessOwnershipStructure = businessOwnershipStructure;
    return this;
  }

   /**
   * The type of business covered by the insurance, according to the value list [BusinessOwnershipType](#businessownershiptype)
   * @return businessOwnershipStructure
  **/
  @Schema(description = "The type of business covered by the insurance, according to the value list [BusinessOwnershipType](#businessownershiptype)")
  public Objekt getBusinessOwnershipStructure() {
    return businessOwnershipStructure;
  }

  public void setBusinessOwnershipStructure(Objekt businessOwnershipStructure) {
    this.businessOwnershipStructure = businessOwnershipStructure;
  }

  public GeneralLiabilityCommercialPolicy businessNumberOfEmployees(String businessNumberOfEmployees) {
    this.businessNumberOfEmployees = businessNumberOfEmployees;
    return this;
  }

   /**
   * Number of employees working for the company
   * @return businessNumberOfEmployees
  **/
  @Schema(description = "Number of employees working for the company")
  public String getBusinessNumberOfEmployees() {
    return businessNumberOfEmployees;
  }

  public void setBusinessNumberOfEmployees(String businessNumberOfEmployees) {
    this.businessNumberOfEmployees = businessNumberOfEmployees;
  }

  public GeneralLiabilityCommercialPolicy industryType(String industryType) {
    this.industryType = industryType;
    return this;
  }

   /**
   * The industry type (code) according to the worldwide standard GICS
   * @return industryType
  **/
  @Schema(description = "The industry type (code) according to the worldwide standard GICS")
  public String getIndustryType() {
    return industryType;
  }

  public void setIndustryType(String industryType) {
    this.industryType = industryType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralLiabilityCommercialPolicy generalLiabilityCommercialPolicy = (GeneralLiabilityCommercialPolicy) o;
    return Objects.equals(this.homeBusiness, generalLiabilityCommercialPolicy.homeBusiness) &&
        Objects.equals(this.businessNumberOfLocations, generalLiabilityCommercialPolicy.businessNumberOfLocations) &&
        Objects.equals(this.businessOwnershipStructure, generalLiabilityCommercialPolicy.businessOwnershipStructure) &&
        Objects.equals(this.businessNumberOfEmployees, generalLiabilityCommercialPolicy.businessNumberOfEmployees) &&
        Objects.equals(this.industryType, generalLiabilityCommercialPolicy.industryType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(homeBusiness, businessNumberOfLocations, businessOwnershipStructure, businessNumberOfEmployees, industryType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralLiabilityCommercialPolicy {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    homeBusiness: ").append(toIndentedString(homeBusiness)).append("\n");
    sb.append("    businessNumberOfLocations: ").append(toIndentedString(businessNumberOfLocations)).append("\n");
    sb.append("    businessOwnershipStructure: ").append(toIndentedString(businessOwnershipStructure)).append("\n");
    sb.append("    businessNumberOfEmployees: ").append(toIndentedString(businessNumberOfEmployees)).append("\n");
    sb.append("    industryType: ").append(toIndentedString(industryType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
