/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ICDStandard
 */
@JsonAdapter(ICDStandard.Adapter.class)
public enum ICDStandard {
  ICD10WHO("ICD10WHO"),
  ICD10CA("ICD10CA"),
  ICD10GM("ICD10GM"),
  ICD10NL("ICD10NL"),
  ICD10CM("ICD10CM"),
  ICD10PCS("ICD10PCS");

  private String value;

  ICDStandard(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ICDStandard fromValue(String input) {
    for (ICDStandard b : ICDStandard.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ICDStandard> {
    @Override
    public void write(final JsonWriter jsonWriter, final ICDStandard enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ICDStandard read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ICDStandard.fromValue((String)(value));
    }
  }
}
