/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets IdentificationType
 */
@JsonAdapter(IdentificationType.Adapter.class)
public enum IdentificationType {
  PASSPORT("Passport"),
  DRIVERLICENSE("DriverLicense"),
  SSN("SSN"),
  TAXNUMBER("TaxNumber"),
  REFERENCE("Reference"),
  COC("CoC"),
  REGISTRATIONNUMBER("RegistrationNumber");

  private String value;

  IdentificationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IdentificationType fromValue(String input) {
    for (IdentificationType b : IdentificationType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IdentificationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final IdentificationType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public IdentificationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IdentificationType.fromValue((String)(value));
    }
  }
}
