/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Occupation
 */
@JsonAdapter(Occupation.Adapter.class)
public enum Occupation {
  PUBLIC("Public"),
  COMMERCIAL("Commercial"),
  RETIRED("Retired"),
  OTHER("Other");

  private String value;

  Occupation(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Occupation fromValue(String input) {
    for (Occupation b : Occupation.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Occupation> {
    @Override
    public void write(final JsonWriter jsonWriter, final Occupation enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public Occupation read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Occupation.fromValue((String)(value));
    }
  }
}
