/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PolicyChannel
 */
@JsonAdapter(PolicyChannel.Adapter.class)
public enum PolicyChannel {
  BROKER("Broker"),
  AGENT("Agent"),
  PHONE("Phone"),
  EMAIL("Email"),
  WEBSITE("Website"),
  OFFICE("Office");

  private String value;

  PolicyChannel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PolicyChannel fromValue(String input) {
    for (PolicyChannel b : PolicyChannel.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PolicyChannel> {
    @Override
    public void write(final JsonWriter jsonWriter, final PolicyChannel enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PolicyChannel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PolicyChannel.fromValue((String)(value));
    }
  }
}
