/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PolicyPaymentType
 */
@JsonAdapter(PolicyPaymentType.Adapter.class)
public enum PolicyPaymentType {
  PAYMENT_UPFRONT("Payment_Upfront"),
  PAYMENT_AUTHORIZATION("Payment_Authorization"),
  MANUALLY("Manually");

  private String value;

  PolicyPaymentType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PolicyPaymentType fromValue(String input) {
    for (PolicyPaymentType b : PolicyPaymentType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PolicyPaymentType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PolicyPaymentType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PolicyPaymentType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PolicyPaymentType.fromValue((String)(value));
    }
  }
}
