/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PolicyPaymentFrequency
 */
@JsonAdapter(PolicyPaymentFrequency.Adapter.class)
public enum PolicyPaymentFrequency {
  MONTHLY("Monthly"),
  QUARTERLY("Quarterly"),
  SEMI_ANNUALLY("Semi_Annually"),
  ANNUALLY("Annually"),
  SINGLE_PREMIUM("Single_Premium"),
  FORTNIGHTLY("Fortnightly");

  private String value;

  PolicyPaymentFrequency(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PolicyPaymentFrequency fromValue(String input) {
    for (PolicyPaymentFrequency b : PolicyPaymentFrequency.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PolicyPaymentFrequency> {
    @Override
    public void write(final JsonWriter jsonWriter, final PolicyPaymentFrequency enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PolicyPaymentFrequency read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PolicyPaymentFrequency.fromValue((String)(value));
    }
  }
}
