/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;

/**
 * SubClaimAutoInvolved
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-03T11:30:23.717Z[GMT]")
public class SubClaimAutoInvolved extends SubClaim {
  @SerializedName("driver")
  private Objekt driver = null;

  @SerializedName("driverRelationToOwner")
  private String driverRelationToOwner = null;

  @SerializedName("ownerPermissionToDrive")
  private Boolean ownerPermissionToDrive = null;

  @SerializedName("passengers")
  private List<LegalEntityRefOfPerson> passengers = null;

  @SerializedName("reasonForUse")
  private String reasonForUse = null;

  @SerializedName("vehicle")
  private Objekt vehicle = null;

  public SubClaimAutoInvolved driver(Objekt driver) {
    this.driver = driver;
    return this;
  }

   /**
   * A reference to a [LegalEntity](#legalentity) (of type [Person](#person)) driving vehicle, mandatory for the SubClaimAutoInvolved
   * @return driver
  **/
  @Schema(description = "A reference to a [LegalEntity](#legalentity) (of type [Person](#person)) driving vehicle, mandatory for the SubClaimAutoInvolved")
  public Objekt getDriver() {
    return driver;
  }

  public void setDriver(Objekt driver) {
    this.driver = driver;
  }

  public SubClaimAutoInvolved driverRelationToOwner(String driverRelationToOwner) {
    this.driverRelationToOwner = driverRelationToOwner;
    return this;
  }

   /**
   * The relationship of the driver of the vehicle to the owner of the vehicle
   * @return driverRelationToOwner
  **/
  @Schema(description = "The relationship of the driver of the vehicle to the owner of the vehicle")
  public String getDriverRelationToOwner() {
    return driverRelationToOwner;
  }

  public void setDriverRelationToOwner(String driverRelationToOwner) {
    this.driverRelationToOwner = driverRelationToOwner;
  }

  public SubClaimAutoInvolved ownerPermissionToDrive(Boolean ownerPermissionToDrive) {
    this.ownerPermissionToDrive = ownerPermissionToDrive;
    return this;
  }

   /**
   * Boolean value indicating whether the driver had permission to use the vehicle at the time of the accident
   * @return ownerPermissionToDrive
  **/
  @Schema(description = "Boolean value indicating whether the driver had permission to use the vehicle at the time of the accident")
  public Boolean isOwnerPermissionToDrive() {
    return ownerPermissionToDrive;
  }

  public void setOwnerPermissionToDrive(Boolean ownerPermissionToDrive) {
    this.ownerPermissionToDrive = ownerPermissionToDrive;
  }

  public SubClaimAutoInvolved passengers(List<LegalEntityRefOfPerson> passengers) {
    this.passengers = passengers;
    return this;
  }

  public SubClaimAutoInvolved addPassengersItem(LegalEntityRefOfPerson passengersItem) {
    if (this.passengers == null) {
      this.passengers = new ArrayList<LegalEntityRefOfPerson>();
    }
    this.passengers.add(passengersItem);
    return this;
  }

   /**
   * An list of references to [LegalEntities](#legalentity) (of type [Person](#person)) that were passengers in the vehicle
   * @return passengers
  **/
  @Schema(description = "An list of references to [LegalEntities](#legalentity) (of type [Person](#person)) that were passengers in the vehicle")
  public List<LegalEntityRefOfPerson> getPassengers() {
    return passengers;
  }

  public void setPassengers(List<LegalEntityRefOfPerson> passengers) {
    this.passengers = passengers;
  }

  public SubClaimAutoInvolved reasonForUse(String reasonForUse) {
    this.reasonForUse = reasonForUse;
    return this;
  }

   /**
   * The reason for using the vehicle at the time of the accident, as provided by the driver of the vehicle
   * @return reasonForUse
  **/
  @Schema(description = "The reason for using the vehicle at the time of the accident, as provided by the driver of the vehicle")
  public String getReasonForUse() {
    return reasonForUse;
  }

  public void setReasonForUse(String reasonForUse) {
    this.reasonForUse = reasonForUse;
  }

  public SubClaimAutoInvolved vehicle(Objekt vehicle) {
    this.vehicle = vehicle;
    return this;
  }

   /**
   * Represents the involved vehicle of type [Vehicle](#vehicle)
   * @return vehicle
  **/
  @Schema(description = "Represents the involved vehicle of type [Vehicle](#vehicle)")
  public Objekt getVehicle() {
    return vehicle;
  }

  public void setVehicle(Objekt vehicle) {
    this.vehicle = vehicle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubClaimAutoInvolved subClaimAutoInvolved = (SubClaimAutoInvolved) o;
    return Objects.equals(this.driver, subClaimAutoInvolved.driver) &&
        Objects.equals(this.driverRelationToOwner, subClaimAutoInvolved.driverRelationToOwner) &&
        Objects.equals(this.ownerPermissionToDrive, subClaimAutoInvolved.ownerPermissionToDrive) &&
        Objects.equals(this.passengers, subClaimAutoInvolved.passengers) &&
        Objects.equals(this.reasonForUse, subClaimAutoInvolved.reasonForUse) &&
        Objects.equals(this.vehicle, subClaimAutoInvolved.vehicle) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(driver, driverRelationToOwner, ownerPermissionToDrive, passengers, reasonForUse, vehicle, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubClaimAutoInvolved {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
    sb.append("    driverRelationToOwner: ").append(toIndentedString(driverRelationToOwner)).append("\n");
    sb.append("    ownerPermissionToDrive: ").append(toIndentedString(ownerPermissionToDrive)).append("\n");
    sb.append("    passengers: ").append(toIndentedString(passengers)).append("\n");
    sb.append("    reasonForUse: ").append(toIndentedString(reasonForUse)).append("\n");
    sb.append("    vehicle: ").append(toIndentedString(vehicle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
