/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ThirdParty
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-03T11:30:23.717Z[GMT]")
public class ThirdParty extends AdditionalFieldsBase {
  @SerializedName("legalEntityRef")
  private LegalEntityRef legalEntityRef = null;

  @SerializedName("customRole")
  private String customRole = null;

  @SerializedName("object")
  private Objekt object = null;

  public ThirdParty legalEntityRef(LegalEntityRef legalEntityRef) {
    this.legalEntityRef = legalEntityRef;
    return this;
  }

   /**
   * Reference of the legal entity that is the third party
   * @return legalEntityRef
  **/
  @Schema(required = true, description = "Reference of the legal entity that is the third party")
  public LegalEntityRef getLegalEntityRef() {
    return legalEntityRef;
  }

  public void setLegalEntityRef(LegalEntityRef legalEntityRef) {
    this.legalEntityRef = legalEntityRef;
  }

  public ThirdParty customRole(String customRole) {
    this.customRole = customRole;
    return this;
  }

   /**
   * A custom role for the third party legal entity
   * @return customRole
  **/
  @Schema(description = "A custom role for the third party legal entity")
  public String getCustomRole() {
    return customRole;
  }

  public void setCustomRole(String customRole) {
    this.customRole = customRole;
  }

  public ThirdParty object(Objekt object) {
    this.object = object;
    return this;
  }

   /**
   * Object that belongs to the legal entity that is the third party
   * @return object
  **/
  @Schema(description = "Object that belongs to the legal entity that is the third party")
  public Objekt getObject() {
    return object;
  }

  public void setObject(Objekt object) {
    this.object = object;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThirdParty thirdParty = (ThirdParty) o;
    return Objects.equals(this.legalEntityRef, thirdParty.legalEntityRef) &&
        Objects.equals(this.customRole, thirdParty.customRole) &&
        Objects.equals(this.object, thirdParty.object) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalEntityRef, customRole, object, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThirdParty {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    legalEntityRef: ").append(toIndentedString(legalEntityRef)).append("\n");
    sb.append("    customRole: ").append(toIndentedString(customRole)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
