/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets VehicleLicensePlateStates
 */
@JsonAdapter(VehicleLicensePlateStates.Adapter.class)
public enum VehicleLicensePlateStates {
  AL("AL"),
  AK("AK"),
  AS("AS"),
  AZ("AZ"),
  AR("AR"),
  CA("CA"),
  CO("CO"),
  CT("CT"),
  DE("DE"),
  DC("DC"),
  FL("FL"),
  GA("GA"),
  GU("GU"),
  HI("HI"),
  ID("ID"),
  IL("IL"),
  IN("IN"),
  IA("IA"),
  KS("KS"),
  KY("KY"),
  LA("LA"),
  ME("ME"),
  MD("MD"),
  MA("MA"),
  MI("MI"),
  MN("MN"),
  MS("MS"),
  MO("MO"),
  MT("MT"),
  NE("NE"),
  NV("NV"),
  NH("NH"),
  NJ("NJ"),
  NY("NY"),
  NC("NC"),
  ND("ND"),
  MP("MP"),
  OH("OH"),
  OK("OK"),
  OR("OR"),
  PA("PA"),
  PR("PR"),
  RI("RI"),
  SC("SC"),
  SD("SD"),
  TN("TN"),
  TX("TX"),
  UM("UM"),
  UT("UT"),
  VT("VT"),
  VI("VI"),
  VA("VA"),
  WA("WA"),
  WV("WV"),
  WI("WI"),
  WY("WY");

  private String value;

  VehicleLicensePlateStates(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static VehicleLicensePlateStates fromValue(String input) {
    for (VehicleLicensePlateStates b : VehicleLicensePlateStates.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<VehicleLicensePlateStates> {
    @Override
    public void write(final JsonWriter jsonWriter, final VehicleLicensePlateStates enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public VehicleLicensePlateStates read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return VehicleLicensePlateStates.fromValue((String)(value));
    }
  }
}
