/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets VehicleSpecialType
 */
@JsonAdapter(VehicleSpecialType.Adapter.class)
public enum VehicleSpecialType {
  TAXI("Taxi"),
  RACING("Racing"),
  TRUCK("Truck"),
  TRAILER("Trailer"),
  ANTIQUE("Antique"),
  CLASSIC("Classic"),
  VINTAGE("Vintage"),
  DIPLOMATIC("Diplomatic"),
  AGRICULTURAL("Agricultural"),
  RENTAL("Rental"),
  MILITARY("Military"),
  BUS("Bus");

  private String value;

  VehicleSpecialType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static VehicleSpecialType fromValue(String input) {
    for (VehicleSpecialType b : VehicleSpecialType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<VehicleSpecialType> {
    @Override
    public void write(final JsonWriter jsonWriter, final VehicleSpecialType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public VehicleSpecialType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return VehicleSpecialType.fromValue((String)(value));
    }
  }
}
