/*
 * FRISS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ClaimScreeningRequestOfAutoPolicy;
import io.swagger.client.model.ClaimScreeningRequestOfGeneralLiabilityCommercialPolicy;
import io.swagger.client.model.ClaimScreeningRequestOfGeneralLiabilityPrivatePolicy;
import io.swagger.client.model.ClaimScreeningRequestOfHealthPolicy;
import io.swagger.client.model.ClaimScreeningRequestOfHomePolicy;
import io.swagger.client.model.ClaimScreeningRequestOfPolicy;
import io.swagger.client.model.ClaimScreeningRequestResult;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DetectionVApi
 */
@Ignore
public class DetectionVApiTest {

    private final DetectionVApi api = new DetectionVApi();

    /**
     * Send a claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPostTest() throws Exception {
        ClaimScreeningRequestOfPolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost(body, version);

        // TODO: test validations
    }
    /**
     * Send auto claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPost2Test() throws Exception {
        ClaimScreeningRequestOfAutoPolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost2(body, version);

        // TODO: test validations
    }
    /**
     * Send home claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPost3Test() throws Exception {
        ClaimScreeningRequestOfHomePolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost3(body, version);

        // TODO: test validations
    }
    /**
     * Send health claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPost4Test() throws Exception {
        ClaimScreeningRequestOfHealthPolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost4(body, version);

        // TODO: test validations
    }
    /**
     * Send general liability commercial claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPost5Test() throws Exception {
        ClaimScreeningRequestOfGeneralLiabilityCommercialPolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost5(body, version);

        // TODO: test validations
    }
    /**
     * Send general liability private claim request to detection.
     *
     * Send claim to detection.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void detectionVPost6Test() throws Exception {
        ClaimScreeningRequestOfGeneralLiabilityPrivatePolicy body = null;
        String version = null;
        ClaimScreeningRequestResult response = api.detectionVPost6(body, version);

        // TODO: test validations
    }
}
